name: Test Deploy iShop Backend

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test SSH connection
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: root
          key: ${{ secrets.DO_SSH_KEY }}
          port: 22
          script: |
            echo "SSH connection successful!"
            whoami
            pwd

      - name: Copy files to server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DO_HOST }}
          username: root
          key: ${{ secrets.DO_SSH_KEY }}
          port: 22
          source: "."
          target: "/var/www/ishopBackend"
          overwrite: true

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: root
          key: ${{ secrets.DO_SSH_KEY }}
          port: 22
          envs: NODE_ENV,DATABASE_URL,JWT_SECRET,PORT
          script: |
            cd /var/www/ishopBackend
            # Create .env file from secrets
            cat > .env << EOF
            NODE_ENV=${NODE_ENV}
            DATABASE_URL=${DATABASE_URL}
            JWT_SECRET=${JWT_SECRET}
            PORT=${PORT}
            EOF
            docker compose down || true
            docker compose build --no-cache
            docker compose up -d
        env:
          NODE_ENV: ${{ secrets.NODE_ENV }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
          PORT: ${{ secrets.PORT }}